"""Gradio web UI for the Doc Query AI chatbot.

Provides a browser-based interface for asking questions about indexed PDF
documents and uploading new PDFs to re-index the vector store.

Usage:
    python app.py
"""

import os  # Extract filenames from upload paths

import gradio as gr  # Web UI framework for the chat interface
from dotenv import load_dotenv  # Load API keys from a .env file

from rag.chain import build_rag_chain  # Build the retrieval + LLM chain
from rag.ingest import load_vector_store, reindex_vector_store  # Load or re-index PDF vectors

load_dotenv()  # Read GOOGLE_API_KEY and other secrets from .env

PDF_PATH = "documents/TechCorp_Official_Employee_Handbook.pdf"  # Default document loaded at startup

_vector_db = None  # Chroma vector store; initialised by init_pipeline()
_rag_chain = None  # LCEL chain; initialised by init_pipeline()


def init_pipeline(pdf_path: str = PDF_PATH) -> None:
    """Load the vector store and build the RAG chain.

    Args:
        pdf_path: Filesystem path to the PDF to index when no store exists.
    """
    global _vector_db, _rag_chain
    print("Initialising RAG pipeline...")
    _vector_db = load_vector_store(pdf_path)  # Load existing store or ingest the default PDF
    _rag_chain = build_rag_chain(_vector_db)  # Wire retriever → prompt → LLM → parser
    print("Ready.\n")


def answer(question: str, history: list) -> str:
    """Handle a chat message from the Gradio interface.

    Args:
        question: The user's natural-language question.
        history: Conversation history supplied by Gradio (unused; chain is stateless).

    Returns:
        str: A plain-text answer generated by the RAG chain.
    """
    if not question.strip():
        return "Please enter a question."  # Reject empty submissions early

    if _rag_chain is None:
        return "RAG pipeline is not initialised."  # Guard against use before init_pipeline()

    return _rag_chain.invoke(question)  # Retrieve context and generate an answer


def _resolve_upload_path(file) -> str | None:
    """Extract the on-disk PDF path from a Gradio file upload.

    Gradio 6 passes a ``FileData`` object with a ``path`` attribute. Older
    versions and test doubles may supply a plain string or an object with
    ``name``.

    Args:
        file: Gradio upload value, file-like object, path string, or dict.

    Returns:
        str | None: Absolute or server-side path to the uploaded PDF, or
            ``None`` when no path can be resolved.
    """
    if file is None:
        return None
    if isinstance(file, str):
        return file
    if isinstance(file, dict):
        return file.get("path") or file.get("name")
    return getattr(file, "path", None) or getattr(file, "name", None)


def _display_name_for_upload(file, pdf_path: str) -> str:
    """Return a human-readable filename for status messages.

    Args:
        file: Original Gradio upload value.
        pdf_path: Resolved filesystem path to the uploaded PDF.

    Returns:
        str: Original upload name when available, otherwise the path basename.
    """
    if isinstance(file, dict):
        return file.get("orig_name") or os.path.basename(pdf_path)
    orig_name = getattr(file, "orig_name", None)
    return orig_name or os.path.basename(pdf_path)


def ingest_pdf(file) -> str:
    """Re-index a newly uploaded PDF and rebuild the RAG chain.

    Resets the existing ChromaDB collection in place (reusing the live client)
    and embeds the uploaded PDF's chunks, then rebuilds the chain.

    Args:
        file: Gradio ``FileData`` upload whose ``path`` points to the PDF on disk.

    Returns:
        str: A status message confirming which file was indexed, or an
            error hint when no file was provided.
    """
    global _vector_db, _rag_chain  # Replace the module-level store and chain references

    pdf_path = _resolve_upload_path(file)  # Gradio 6 provides FileData.path, not .name
    if not pdf_path:
        return "No file uploaded."  # Guard against clicking Index with no file selected

    _vector_db = reindex_vector_store(_vector_db, pdf_path)  # Reset collection in place
    _rag_chain = build_rag_chain(_vector_db)  # Rebuild the chain against the new store
    return f"Indexed: {_display_name_for_upload(file, pdf_path)}"


with gr.Blocks(title="Doc Query AI") as demo:
    gr.Markdown(
        """
        # Doc Query AI
        Ask natural-language questions about your PDF documents, powered by
        **ChromaDB** vector search and **Google Gemini**.
        """
    )  # Page title and description shown at the top of the UI

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("### Upload a new document")  # Section heading for the upload panel
            upload = gr.File(label="PDF file", file_types=[".pdf"])  # File picker restricted to PDFs
            upload_btn = gr.Button("Index document")  # Trigger re-indexing of the uploaded file
            upload_status = gr.Textbox(label="Status", interactive=False)  # Read-only status feedback
            upload_btn.click(fn=ingest_pdf, inputs=upload, outputs=upload_status)  # Wire button to handler

        with gr.Column(scale=3):
            gr.ChatInterface(
                fn=answer,
                examples=[
                    "What is the vacation policy?",
                    "What are the code of conduct rules?",
                    "How does the performance review process work?",
                ],
            )  # Main chat panel with starter example questions

if __name__ == "__main__":
    init_pipeline()  # Build the vector store and chain before serving requests
    demo.launch()  # Start the local Gradio server (default: http://127.0.0.1:7860)
