"""Gradio web UI for the Doc Query AI chatbot.

Provides a browser-based interface for asking questions about indexed PDF
documents and uploading new PDFs to re-index the vector store.

Usage:
    python app.py
"""

import gc  # Force garbage collection to release ChromaDB connections
import os  # Check paths and extract filenames
import shutil  # Remove the old ChromaDB directory during re-indexing

import gradio as gr  # Web UI framework for the chat interface
from dotenv import load_dotenv  # Load API keys from a .env file

from rag.chain import build_rag_chain  # Build the retrieval + LLM chain
from rag.ingest import CHROMA_DIR, build_vector_store, load_vector_store  # Ingest or load PDF vectors

load_dotenv()  # Read GOOGLE_API_KEY and other secrets from .env

PDF_PATH = "documents/TechCorp_Official_Employee_Handbook.pdf"  # Default document loaded at startup

_vector_db = None  # Chroma vector store; initialised by init_pipeline()
_rag_chain = None  # LCEL chain; initialised by init_pipeline()


def init_pipeline(pdf_path: str = PDF_PATH) -> None:
    """Load the vector store and build the RAG chain.

    Args:
        pdf_path: Filesystem path to the PDF to index when no store exists.
    """
    global _vector_db, _rag_chain
    print("Initialising RAG pipeline...")
    _vector_db = load_vector_store(pdf_path)  # Load existing store or ingest the default PDF
    _rag_chain = build_rag_chain(_vector_db)  # Wire retriever → prompt → LLM → parser
    print("Ready.\n")


def answer(question: str, history: list) -> str:
    """Handle a chat message from the Gradio interface.

    Args:
        question: The user's natural-language question.
        history: Conversation history supplied by Gradio (unused; chain is stateless).

    Returns:
        str: A plain-text answer generated by the RAG chain.
    """
    if not question.strip():
        return "Please enter a question."  # Reject empty submissions early

    if _rag_chain is None:
        return "RAG pipeline is not initialised."  # Guard against use before init_pipeline()

    return _rag_chain.invoke(question)  # Retrieve context and generate an answer


def ingest_pdf(file) -> str:
    """Re-index a newly uploaded PDF and rebuild the RAG chain.

    Releases the existing ChromaDB connection, deletes the persisted store,
    embeds the uploaded PDF, and swaps in a fresh chain backed by the new
    vectors.

    Args:
        file: Gradio file object with a ``name`` attribute pointing to the
            uploaded PDF on disk.

    Returns:
        str: A status message confirming which file was indexed, or an
            error hint when no file was provided.
    """
    global _vector_db, _rag_chain  # Replace the module-level store and chain references

    if file is None:
        return "No file uploaded."  # Guard against clicking Index with no file selected

    # Release the ChromaDB connection before deleting the directory.
    # Without this the underlying SQLite file stays locked and the new
    # Chroma.from_documents() call fails with "readonly database".
    _vector_db = None  # Drop the reference to the open Chroma client
    _rag_chain = None  # Drop the reference to the chain that wraps the old retriever
    gc.collect()  # Force Python to close the underlying SQLite connection

    if os.path.exists(CHROMA_DIR):
        shutil.rmtree(CHROMA_DIR)  # Remove the old persisted vector store

    _vector_db = build_vector_store(file.name)  # Embed the uploaded PDF into a fresh store
    _rag_chain = build_rag_chain(_vector_db)  # Rebuild the chain against the new store
    return f"Indexed: {os.path.basename(file.name)}"  # Confirm success in the UI


with gr.Blocks(title="Doc Query AI") as demo:
    gr.Markdown(
        """
        # Doc Query AI
        Ask natural-language questions about your PDF documents, powered by
        **ChromaDB** vector search and **Google Gemini**.
        """
    )  # Page title and description shown at the top of the UI

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("### Upload a new document")  # Section heading for the upload panel
            upload = gr.File(label="PDF file", file_types=[".pdf"])  # File picker restricted to PDFs
            upload_btn = gr.Button("Index document")  # Trigger re-indexing of the uploaded file
            upload_status = gr.Textbox(label="Status", interactive=False)  # Read-only status feedback
            upload_btn.click(fn=ingest_pdf, inputs=upload, outputs=upload_status)  # Wire button to handler

        with gr.Column(scale=3):
            gr.ChatInterface(
                fn=answer,
                examples=[
                    "What is the vacation policy?",
                    "What are the code of conduct rules?",
                    "How does the performance review process work?",
                ],
            )  # Main chat panel with starter example questions

if __name__ == "__main__":
    init_pipeline()  # Build the vector store and chain before serving requests
    demo.launch()  # Start the local Gradio server (default: http://127.0.0.1:7860)
